// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxcafqhaybawdkdstlqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Y2FmcWhheWJhd2RrZHN0bHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjM3NjgsImV4cCI6MjA2NTczOTc2OH0.HelmlPUpUcqksxaRA9m3gMVTuvX4cO5AkhMCidIlJrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);